FROM python:3.10

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1 

RUN mkdir /media/documents

RUN pip install --upgrade pip

COPY . .

RUN pip install -r requirements.txt

EXPOSE 8000

ARG SQL_DB_NAME 
ARG SQL_DB_USER 
ARG SQL_DB_PASSWORD 
ARG SQL_DB_HOST 
ARG SQL_DB_PORT 
ARG NOSQL_DB_NAME 
ARG NOSQL_DB_USER 
ARG NOSQL_DB_PASSWORD 
ARG NOSQL_DB_HOST 
ARG NOSQL_DB_PORT 
ARG APP_URL 
ARG DOMAIN 
ARG JWT_SECRET 
ARG APP_SECRET 
ARG DEFAULT_FROM_EMAIL 
ARG EMAIL_HOST 
ARG EMAIL_HOST_USER 
ARG EMAIL_HOST_PASSWORD 
ARG EMAIL_PORT 
ARG EMAIL_USE_TLS 

ENV SQL_DB_NAME ${APP_SECRET}
ENV SQL_DB_USER ${APP_SECRET}
ENV SQL_DB_PASSWORD ${APP_SECRET}
ENV SQL_DB_HOST ${APP_SECRET}
ENV SQL_DB_PORT ${APP_SECRET}
ENV NOSQL_DB_NAME ${APP_SECRET}
ENV NOSQL_DB_USER ${APP_SECRET}
ENV NOSQL_DB_PASSWORD ${APP_SECRET}
ENV NOSQL_DB_HOST ${APP_SECRET}
ENV NOSQL_DB_PORT ${APP_SECRET}
ENV APP_URL ${APP_SECRET}
ENV DOMAIN ${APP_SECRET}
ENV JWT_SECRET ${APP_SECRET}
ENV APP_SECRET ${APP_SECRET}
ENV DEFAULT_FROM_EMAIL ${APP_SECRET}
ENV EMAIL_HOST ${APP_SECRET}
ENV EMAIL_HOST_USER ${APP_SECRET}
ENV EMAIL_HOST_PASSWORD ${APP_SECRET}
ENV EMAIL_PORT ${APP_SECRET}
ENV EMAIL_USE_TLS ${APP_SECRET}

ENTRYPOINT [ "docker-entrypoint.sh" ]