name: Neuroparser CD Pipeline
on:
    push:
        branches:
            - develop
jobs:
    build-stage-deploy:
        runs-on: self-hosted
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

              
            - name: Setup AWS ECR Details
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ secrets.AWS_REGION }}
            
            - name: Login to Amazon ECR
              id: login-pf-aws-ecr
              uses: aws-actions/amazon-ecr-login@v1

            - name: Build and push the tagged docker image to Amazon ECR
              env:
                ECR_REGISTRY: ${{ steps.login-pf-aws-ecr.outputs.registry }}
                ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPO }}
                IMAGE_TAG: latest
              run: |                
                echo SQL_DB_NAME=${{secrets.SQLDB_CREDS_NAME}} SQL_DB_USER=${{secrets.SQLDB_CREDS_USERNAME}}
                echo $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
                docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
                docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
                
            - name: Deploy to EC2
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.USER_HOST }}
                password: ${{ secrets.PASSWORD_HOST }}
                script: docker container run -d --name web_service --network host $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
