name: Neuroparser CD Pipeline
on:
    push:
        branches:
            - develop
jobs:
    build-stage-deploy:
        runs-on: self-hosted
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Login to Docker HUB
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_TOKEN }}
            
            - name: Build and Push Docker image
              uses: docker/build-push-action@v5
              with:
                context: .
                push: true
                tags: jiji66/neuroparser:${{ github.sha }}
            
            - name: Deploy to EC2
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.USER_HOST }}
                password: ${{ secrets.PASSWORD_HOST }}
                script: docker container run -d --name web_service --network host jiji66/neuroparser:${{ github.sha }}
